export enum PointFeatureType {
  LIBRARY = 'library',
  COMMUNITY_CENTER = 'community_center',
  PARK = 'park',
  SCHOOL = 'school',
  CCF = 'cc_family',
  CCC = 'cc_center',
  CA = 'assault',
  CBR = 'burg',
  CD = 'drug',
  CT = 'theft',
  CO = 'other',
  CW = 'weapon',
  HC = 'health',
  SEARCH = 'search',
  SICK = 'sick',
  LEAD0= 'lead0',
  LEAD1= 'lead1',
  LEAD2= 'lead2',
  LEAD3= 'lead3',
  LEAD4= 'lead4',
  LEAD5= 'lead5',
  LEAD6= 'lead6',
  COVIDVACC='covidvacc',
  COVIDCASE= 'covidcase',

}
